var chai = require('chai')
var chaiHttp = require('chai-http')
var server = require('../../app')

chai.should();

chai.use(chaiHttp);


describe('CHECK GET PLACE REVIEWS', function(){

    it('check with wrong url', function(done){
        chai.request(server)
            .get('/placeRevies/ChIJbzYnQte8woARJaqqFVpKeNo')
            .end((err,resp)=>{                
                resp.should.have.status(404)
                resp.body.should.have.property('error')
                resp.body.error.should.have.property('message')
                done()
            })
    }).timeout(120000)

    it('check with wrong url', function(done){
        chai.request(server)
            .get('/placeReviews/ChIJbzYnQte8woARJaqqFVpKeNo')
            .end((err,resp)=>{
                resp.should.have.status(200)
                resp.body.should.have.property('placeName')
                resp.body.should.have.property('address')
                resp.body.should.have.property('bestReview')
                resp.body.should.have.property('placeId')
                resp.body.should.have.property('img')
                resp.body.should.have.property('lat')
                resp.body.should.have.property('lng')
                resp.body.should.have.property('negativePresentage')
                resp.body.should.have.property('positivePresentage')
                resp.body.should.have.property('naturalPresentage')
                resp.body.should.have.property('rating')
                resp.body.should.have.property('reviews')
                done()
            })
    }).timeout(120000)

    it('check with wrong url', function(done){
        chai.request(server)
            .get('/placeReviews/ChIJJ7zkh3es_ToRfBitXXGg2c0')
            .end((err,resp)=>{
                resp.should.have.status(200)
                resp.body.should.have.property('placeName')
                resp.body.should.have.property('address')
                resp.body.should.have.property('bestReview')
                resp.body.should.have.property('placeId')
                resp.body.should.have.property('img')
                resp.body.should.have.property('lat')
                resp.body.should.have.property('lng')
                resp.body.should.have.property('negativePresentage')
                resp.body.should.have.property('positivePresentage')
                resp.body.should.have.property('naturalPresentage')
                resp.body.should.have.property('rating')
                resp.body.should.have.property('reviews')
                done()
            })
    }).timeout(120000)

    it('check with wrong url', function(done){
        chai.request(server)
            .get('/placeReviews/ChIJl5yE6Jv1_DoRjhdtagikgZY')
            .end((err,resp)=>{
                resp.should.have.status(200)
                resp.body.should.have.property('placeName')
                resp.body.should.have.property('address')
                resp.body.should.have.property('bestReview')
                resp.body.should.have.property('placeId')
                resp.body.should.have.property('img')
                resp.body.should.have.property('lat')
                resp.body.should.have.property('lng')
                resp.body.should.have.property('negativePresentage')
                resp.body.should.have.property('positivePresentage')
                resp.body.should.have.property('naturalPresentage')
                resp.body.should.have.property('rating')
                resp.body.should.have.property('reviews')
                done()
            })
    }).timeout(120000)

    it('check with wrong url', function(done){
        chai.request(server)
            .get('/placeReviews/ChIJtfdplWNf_DoRp8dlDcpuhfI')
            .end((err,resp)=>{
                resp.should.have.status(200)
                resp.body.should.have.property('placeName')
                resp.body.should.have.property('address')
                resp.body.should.have.property('bestReview')
                resp.body.should.have.property('placeId')
                resp.body.should.have.property('img')
                resp.body.should.have.property('lat')
                resp.body.should.have.property('lng')
                resp.body.should.have.property('negativePresentage')
                resp.body.should.have.property('positivePresentage')
                resp.body.should.have.property('naturalPresentage')
                resp.body.should.have.property('rating')
                resp.body.should.have.property('reviews')
                done()
            })
    }).timeout(120000)

    it('check with wrong url', function(done){
        chai.request(server)
            .get('/placeReviews/ChIJnbBnzKUA4zoRuFeA0cQWfYQ')
            .end((err,resp)=>{
                resp.should.have.status(200)
                resp.body.should.have.property('placeName')
                resp.body.should.have.property('address')
                resp.body.should.have.property('bestReview')
                resp.body.should.have.property('placeId')
                resp.body.should.have.property('img')
                resp.body.should.have.property('lat')
                resp.body.should.have.property('lng')
                resp.body.should.have.property('negativePresentage')
                resp.body.should.have.property('positivePresentage')
                resp.body.should.have.property('naturalPresentage')
                resp.body.should.have.property('rating')
                resp.body.should.have.property('reviews')
                done()
            })
    }).timeout(120000)

    it('check with wrong url', function(done){
        chai.request(server)
            .get('/placeReviews/ChIJQRJv0Zb1_DoRjWifejv6EvQ')
            .end((err,resp)=>{
                resp.should.have.status(200)
                resp.body.should.have.property('placeName')
                resp.body.should.have.property('address')
                resp.body.should.have.property('bestReview')
                resp.body.should.have.property('placeId')
                resp.body.should.have.property('img')
                resp.body.should.have.property('lat')
                resp.body.should.have.property('lng')
                resp.body.should.have.property('negativePresentage')
                resp.body.should.have.property('positivePresentage')
                resp.body.should.have.property('naturalPresentage')
                resp.body.should.have.property('rating')
                resp.body.should.have.property('reviews')
                done()
            })
    }).timeout(120000)

    it('check with wrong url', function(done){
        chai.request(server)
            .get('/placeReviews/ChIJfbxYZb31_DoRVO6nFKyDpl4')
            .end((err,resp)=>{
                resp.should.have.status(200)
                resp.body.should.have.property('placeName')
                resp.body.should.have.property('address')
                resp.body.should.have.property('bestReview')
                resp.body.should.have.property('placeId')
                resp.body.should.have.property('img')
                resp.body.should.have.property('lat')
                resp.body.should.have.property('lng')
                resp.body.should.have.property('negativePresentage')
                resp.body.should.have.property('positivePresentage')
                resp.body.should.have.property('naturalPresentage')
                resp.body.should.have.property('rating')
                resp.body.should.have.property('reviews')
                done()
            })
    }).timeout(120000)

    it('check with wrong url', function(done){
        chai.request(server)
            .get('/placeReviews/ChIJ55TqL2CK_DoRqXURrsiiGgk')
            .end((err,resp)=>{
                resp.should.have.status(200)
                resp.body.should.have.property('placeName')
                resp.body.should.have.property('address')
                resp.body.should.have.property('bestReview')
                resp.body.should.have.property('placeId')
                resp.body.should.have.property('img')
                resp.body.should.have.property('lat')
                resp.body.should.have.property('lng')
                resp.body.should.have.property('negativePresentage')
                resp.body.should.have.property('positivePresentage')
                resp.body.should.have.property('naturalPresentage')
                resp.body.should.have.property('rating')
                resp.body.should.have.property('reviews')
                done()
            })
    }).timeout(120000)

})